language: node_js
sudo: false
node_js:
  - '4.2'

cache:
  directories:
    - node_modules
    - app/bower_components

branches:
  except:
    - /^g3_.*$/

env:
  matrix:
    - JOB=ci-checks
  global:
    - CXX=g++-4.8  # node 4 likes the G++ v4.8 compiler
    - LOGS_DIR=/tmp/junnyria-web/logs

# node 4 likes the G++ v4.8 compiler
# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  # - npm config set registry http://23.251.144.68
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  #- npm install -g npm@2.5
  # Install npm dependencies and ensure that npm cache is not stale
  - npm i

before_script:
  - npm i -g grunt-cli

script:
  - grunt build
  - grunt test

after_script:
  - bower install

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b2a1fdd21cfa14250e88
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false